### ISSUE TITLE
InvalidDigitsReceived missing from documentation

### ISSUE THREAD

**Issue by InterLinked1** [awsdocs/amazon-chime-developer-guide#10]
I recently tested out one of the Chime SDK workshops and in the process of doing so, encountered the following error:

`InvalidDigitsReceived`

The meaning is pretty easy to figure out, by name and by context, but it's not in any of the documentation or listed as an error that could be received. For example, no mention of it here: https://docs.aws.amazon.com/chime-sdk/latest/dg/speak-and-get-digits.html

(Or anywhere else in the repo for that matter)

If the tables such as on the page above are intended to be exhaustive, then I'd say this indicates a documentation bug as some of the common error conditions are missing.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
