### ISSUE TITLE
Concatenation pipelines and compositing

### ISSUE THREAD

**Issue by jagregory** [awsdocs/amazon-chime-developer-guide#11]
The published documentation for [Concatenation pipelines](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-concat-pipe.html) seems to be the only place that mentions these capabilities, the link to the API docs for [CreateMediaConcatenationPipeline](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateMediaConcatenationPipeline) is 404, and the source in this repo seems to have disappeared.

Is this API something that is going to return?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
