### ISSUE TITLE
Background Blur documentation disappeared

### ISSUE THREAD

**Issue by MitchTalmadge** [awsdocs/amazon-chime-developer-guide#9]
https://github.com/awsdocs/amazon-chime-sdk-developer-guide/blob/master/doc_source/background-blur.md used to be displayed at https://docs.aws.amazon.com/chime-sdk/latest/dg/background-blur.html. However, this document has gone missing. There is an archived version here: https://web.archive.org/web/20220415163232/https://docs.aws.amazon.com/chime-sdk/latest/dg/background-blur.html

Why did this documentation get removed? Is the feature being deprecated? 
Thanks!

**Comment by dlawty** [comment]
It's not getting deprecated. It's getting better!

Now there is background replacement in addition to the blur. I've always referred to the guide on GitHub. The updated guide (that includes both blur and replacement) is here: https://aws.github.io/amazon-chime-sdk-js/modules/backgroundfilter_video_processor.html.

**Comment by MitchTalmadge** [comment]
Nice, thank you @dlawty ! That is good to hear.
